### ISSUE TITLE
Pulsing red underglow at syntax errors, can be optional?

### ISSUE THREAD

**Issue by pkalbers** [tjkohli/nebula-syntax#4]
I am using atom for latex a lot. Therefore many syntax elements (or simply many of the technical terms or equations) are falsely recognised as errors. The result is a visual overload of red glowing lines in the script. 

Therefore, would it be possible to make this (otherwise very good looking feature) optional?

**Comment by tjkohli** [comment]
@pkalbers Thanks for the feedback!

Since the underlying issue sounds like a problem with the LaTeX package not linting properly, I wouldn't want to complicate Nebula to _hack_ around those bugs.

That being said, I can understand it must be a bit overwhelming to see so many red glows, so here's a possible solution path for you:

1. [Install a (different) LaTeX package](https://atom.io/packages/search?q=latex) to see if that offers better linting.
2. If you've tried them, open an Issue in the GitHub repository of the LaTeX package you're using.
3. Until that's resolved, add the following CSS snippet to your Atom stylesheet ([instructions](http://flight-manual.atom.io/using-atom/sections/basic-customization/#style-tweaks)):
```
.syntax--invalid.syntax--illegal,
.spell-check-misspelling .region {
	animation: none;
}
```

That should disable the red glow altogether.
